const fs = require('fs');
const path = require('path');
const publicDocs = require('./src/api/v1/public/public.docs');

const enDocs = JSON.parse(JSON.stringify(publicDocs));

// Translate Core
enDocs.core.name = "Core";
enDocs.core.description = "Main endpoints and general features of the site.";

enDocs.core.endpoints[0].name = "Get Site";
enDocs.core.endpoints[0].description = "Gets the general information of the site, its template, active features, and content.";

enDocs.core.endpoints[1].name = "Render Page (Home)";
enDocs.core.endpoints[1].description = "Gets the main page (home) of the site along with the site information, ready to be rendered.";

enDocs.core.endpoints[2].name = "Render Page by Slug";
enDocs.core.endpoints[2].description = "Gets the HTML, CSS, and JS of a specific page using its slug, along with the site information.";
enDocs.core.endpoints[2].parameters[0].description = "The slug of the page to render.";

enDocs.core.endpoints[3].name = "Site Documentation";
enDocs.core.endpoints[3].description = "Gets the documentation of the active public routes for the site. Includes only enabled modules.";
enDocs.core.endpoints[3].parameters[0].description = 'If "true", returns only name, path, and method of each endpoint.';

// Translate Blog
enDocs.blog.name = "Blog";
enDocs.blog.description = 'Blog module endpoints to query categories and posts. IMPORTANT: The "content" field of posts returns a JSON object generated by the TipTap editor (based on ProseMirror), NOT an HTML string. Example: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"hello"}]}]}. You must create functions to render this JSON to HTML on the frontend.';

enDocs.blog.endpoints[0].name = "List Categories";
enDocs.blog.endpoints[0].description = "Gets the list of blog categories ordered by name.";

enDocs.blog.endpoints[1].name = "List Posts";
enDocs.blog.endpoints[1].description = "Gets a paginated list of published posts, ordered from newest to oldest.";
enDocs.blog.endpoints[1].parameters[0].description = "Number of results per page (default 10).";
enDocs.blog.endpoints[1].parameters[1].description = "Number of records to skip (default 0).";

enDocs.blog.endpoints[2].name = "Get Post by Slug";
enDocs.blog.endpoints[2].description = "Gets the details of a specific published post using its slug.";
enDocs.blog.endpoints[2].parameters[0].description = "The slug of the post to find.";

// Translate Portfolio
enDocs.portfolio.name = "Portfolio";
enDocs.portfolio.description = "Portfolio module endpoint. Returns all portfolio data (sections, projects, and tech stack) in a single call.";

enDocs.portfolio.endpoints[0].name = "Get Complete Portfolio";
enDocs.portfolio.endpoints[0].description = "Gets all portfolio data: sections, projects, and tech stack items.";

const finalCode = `
"use strict";

const docs = {
  es: ${JSON.stringify(publicDocs, null, 2)},
  en: ${JSON.stringify(enDocs, null, 2)}
};

module.exports = (lang = 'es') => docs[lang] || docs['es'];
`;

fs.writeFileSync(path.join(__dirname, 'src/api/v1/public/public.docs.js'), finalCode);
console.log('Docs translated and updated!');
